image: docker:latest
services:
  - docker:dind
before_script:
  - docker info
  - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"

  - eval $(ssh-agent -s)

  - chmod 400 "$SSH_PRIVATE_KEY"
  - ssh-add "$SSH_PRIVATE_KEY"

  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

  - cp $KNOWN_HOSTS ~/.ssh/known_hosts

stages:
  - build
  - deploy

variables:
  REMOTE_USER: "ubrato"
  REMOTE_HOST: "194.58.96.228"
  REMOTE_PORT: "2022"
  REMOTE_PATH: "/home/ubrato/ubrato"

dev-build:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^stage/ && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=~ /^stage/
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

dev-deploy:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^stage/ && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=~ /^stage/
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT "docker service update --with-registry-auth --force --image registry.ubrato.ru/ubrato/ubrato-front:latest stack_ubrato-front"

prod-build:
  only:
    - main
    - master
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" .
    - docker push "$CI_REGISTRY_IMAGE:latest"

prod-deploy:
  only:
    - master
    - main
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST -p $REMOTE_PORT "docker service update --with-registry-auth --force --image registry.ubrato.ru:5050/ubrato/ubrato-frontts:latest stack_ubrato-front"
