services:
  front:
    image: ubrato-front
    container_name: ubrato-front
    build: .
    restart: unless-stopped
    networks:
      - ubrato-front-network
    ports:
      - "8003:80"

networks:
  ubrato-front-network:
    name: ubrato-front-network
